# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: apcharpe <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/22 12:14:59 by apcharpe          #+#    #+#              #
#    Updated: 2018/08/22 16:24:45 by apcharpe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op
SRCS = f_calculate.c ft_atoi.c ft_putnbr.c ft_putchar.c ft_sum.c ft_subtract.c ft_multiply.c ft_divide.c ft_modulo.c

all :
	gcc $(SRCS) -o $(NAME)

clean :
	/bin/rm -rf $(NAME)
